version: '3'

services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    ports:
    - ${POSTGRESQL_PORT}:5432

  app:
    build: .
    env_file:
      - .env
    environment:
      POSTGRESQL_HOST: postgres
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgres
